# -*- coding: utf-8 -*-
"""STFT-spectrograms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8LqvFTkF4BykAG2adEStyWRl1nXZtdR
"""

def create_stft_spectrogram(audio_file, output_dir, sr=16000, n_fft=2048, hop_length=256):
    y, sr = librosa.load(audio_file, sr=sr)
    stft_spec = np.abs(librosa.stft(y, n_fft=n_fft, hop_length=hop_length))
    stft_spec_db = librosa.amplitude_to_db(stft_spec, ref=np.max)

    plt.figure(figsize=(10, 4))
    librosa.display.specshow(stft_spec_db, sr=sr, hop_length=hop_length, x_axis='time', y_axis='log')
    plt.colorbar(format='%+2.0f dB')
    plt.title('STFT Spectrogram')
    plt.tight_layout()

    filename = os.path.basename(audio_file).split('.')[0] + '_stft.png'
    save_path = os.path.join(output_dir, filename)
    plt.savefig(save_path)
    plt.close()

    print(f'STFT spectrogram saved as {filename}')

if __name__ == '__main__':
    audio_dir = '/content/drive/MyDrive/Summer REU/UnknownDrone'
    output_dir_base = '/content/drive/MyDrive/Summer REU/Unknown Spectrograms'

    os.makedirs(output_dir_base, exist_ok=True)

    file_counter = 0
    total_files_found = 0

    if os.path.isdir(audio_dir):
        print(f"Processing directory: {audio_dir}")
        for category in os.listdir(audio_dir):
            category_path = os.path.join(audio_dir, category)
            output_dir = os.path.join(output_dir_base, category)
            os.makedirs(output_dir, exist_ok=True)

            if os.path.isdir(category_path):
                print(f"Processing subdirectory: {category_path}")
                for file in os.listdir(category_path):
                    if file.endswith('.wav') or file.endswith('.mp3'):
                        total_files_found += 1
                        audio_file = os.path.join(category_path, file)
                        print(f"Processing file: {audio_file}")
                        create_stft_spectrogram(audio_file, output_dir)
                        file_counter += 1
            else:
                print(f"Skipped: {category_path} is not a directory.")
    else:
        print(f"Provided audio directory path '{audio_dir}' is not valid.")

    print(f'Total files found: {total_files_found}')
    print(f'Total files processed: {file_counter}')